/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package dta_berkelompok;

import java.util.Arrays;
import javax.swing.table.DefaultTableModel;
import javax.swing.JOptionPane;

/**
 *
 * @author Laila Nur Azizah (2201010652)
 */
public class frm_interval extends javax.swing.JFrame {
    DefaultTableModel tbmodel=new DefaultTableModel();
    int [] data = new int [0];
    operasi op=new operasi();
    /**
     * Creates new form frm_interval
     */
    public frm_interval() {
        initComponents();
        tbfrekuensi.setModel(tbmodel);
        tbmodel.addColumn("Interval");
        tbmodel.addColumn("Frekuensi");
        tbmodel.addColumn("Tepi Bawah");
        tbmodel.addColumn("Tepi Atas");
        tbmodel.addColumn("Nilai Tengah");
        setE(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tbfrekuensi = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        txmean = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txmedian = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txmodus = new javax.swing.JTextField();
        csimpan = new javax.swing.JButton();
        ctutup = new javax.swing.JButton();
        cproses = new javax.swing.JButton();
        txkelas = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txinterval = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txganti = new javax.swing.JTextField();
        cganti = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        txrerata = new javax.swing.JTextField();
        txbaku = new javax.swing.JTextField();
        txvarians = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        txganti1 = new javax.swing.JTextField();
        cganti1 = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tbfrekuensi.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tbfrekuensi);

        jLabel1.setText("Rata-rata");

        txmean.setEditable(false);

        jLabel2.setText("Median");

        txmedian.setEditable(false);
        txmedian.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txmedianActionPerformed(evt);
            }
        });

        jLabel3.setText("Modus");

        txmodus.setEditable(false);

        csimpan.setText("Masukkan Data");
        csimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                csimpanActionPerformed(evt);
            }
        });

        ctutup.setText("Tutup");
        ctutup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ctutupActionPerformed(evt);
            }
        });

        cproses.setText("proses");
        cproses.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cprosesActionPerformed(evt);
            }
        });

        txkelas.setEditable(false);
        txkelas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txkelasActionPerformed(evt);
            }
        });

        jLabel4.setText("Kelas");

        txinterval.setEditable(false);

        jLabel5.setText("Interval Kelas");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        jLabel6.setText("Tabel Distribusi Frekuensi");

        txganti.setEditable(false);
        txganti.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txgantiActionPerformed(evt);
            }
        });

        cganti.setText("Ganti");
        cganti.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cgantiActionPerformed(evt);
            }
        });

        jLabel7.setText("Masukkan Data Ubah");

        jLabel8.setText("Simpangan Rerata");

        jLabel9.setText("Simpangan Baku");

        jLabel10.setText("Varians");

        txrerata.setEditable(false);

        txbaku.setEditable(false);

        txvarians.setEditable(false);

        jLabel11.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        jLabel11.setText("Ubah Data Sebanyak Yang Diperlukan");

        txganti1.setEditable(false);

        cganti1.setText("Ganti");
        cganti1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cganti1ActionPerformed(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        jLabel12.setText("Ubah Seluruh Frekuensi Data");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(csimpan)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cproses, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(ctutup, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGap(6, 6, 6))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txinterval, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txkelas, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(txmodus, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txmedian, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9)
                            .addComponent(jLabel7)
                            .addComponent(jLabel10)
                            .addComponent(jLabel8))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txganti, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(cganti))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txrerata)
                                    .addComponent(txbaku)
                                    .addComponent(txvarians))
                                .addGap(6, 6, 6))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(38, 38, 38)
                        .addComponent(txmean))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                    .addComponent(txganti1)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(cganti1))
                                .addComponent(jLabel11))
                            .addComponent(jLabel12, javax.swing.GroupLayout.Alignment.TRAILING))))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel6)
                .addGap(316, 316, 316))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {txganti, txganti1});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(jLabel6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 356, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(jLabel1))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txmean, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel2)
                                    .addComponent(txmedian, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel3)
                                    .addComponent(txmodus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txkelas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel4))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txinterval, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel7)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel8)
                                    .addComponent(txrerata, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel9)
                                    .addComponent(txbaku, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txvarians, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel10))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txganti, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(cganti))
                                .addGap(3, 3, 3)))
                        .addComponent(jLabel11)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txganti1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cganti1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel12)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cproses)
                            .addComponent(csimpan))
                        .addGap(18, 18, 18)
                        .addComponent(ctutup)))
                .addContainerGap(49, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {txbaku, txinterval, txkelas, txmean, txmedian, txmodus, txrerata, txvarians});

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void ctutupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ctutupActionPerformed
       dispose();
    }//GEN-LAST:event_ctutupActionPerformed

    private void csimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_csimpanActionPerformed
       StoreData();
        
    }//GEN-LAST:event_csimpanActionPerformed

    private void cprosesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cprosesActionPerformed
        proses();
    }//GEN-LAST:event_cprosesActionPerformed

    private void txkelasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txkelasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txkelasActionPerformed

    private void txmedianActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txmedianActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txmedianActionPerformed

    private void cgantiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cgantiActionPerformed
        String ganti=txganti.getText();
        if (!ganti.equals("")) {
            int sample=Integer.parseInt(ganti);
            String x = JOptionPane.showInputDialog("Jumlah Dari Frekuensi Data Tersebut Yang Diubah");
            if (x!=null) {
              int jmlh=Integer.parseInt(x);
                op.hapus(sample,data,jmlh);
                txganti.setText("");  
            }
        }
    }//GEN-LAST:event_cgantiActionPerformed

    private void txgantiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txgantiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txgantiActionPerformed

    private void cganti1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cganti1ActionPerformed
        String gantiall=txganti1.getText();
        if (!gantiall.equals("")) {
            int sample=Integer.parseInt(gantiall);
            op.hapus(sample,data);
            txganti1.setText("");
        }
    }//GEN-LAST:event_cganti1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frm_interval.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frm_interval.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frm_interval.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frm_interval.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frm_interval().setVisible(true);
            }
        });
    }
    public void StoreData(){
        int no=1;
        String inp1 = JOptionPane.showInputDialog("Masukkan Banyak Data");
        if (inp1!=null) {
        int conv=Integer.parseInt(inp1);
        int inp=conv;
            if (inp>1) {
            int [] newdata = new int [inp]; //temporary array
            for (int i = 0; i < newdata.length; i++) {
                String temp=JOptionPane.showInputDialog("Masukkan Data Ke-: "+no);
                if (temp!=null) {
                    int var=Integer.parseInt(temp);
                    newdata[i]=var;
                    no++;  
                }else{
                    setE(false);
                    break;
                }
            }
            // Copy the new data to the original array
            data = newdata;
            cproses.setEnabled(true);
            txganti.setEditable(true);
            cganti.setEnabled(true);
            txganti1.setEditable(true);
            cganti1.setEnabled(true);
            }else{
            String[] options = {"OK"};
            Object[] optionsArray = options;
            int konf=JOptionPane.showOptionDialog(this, "Jumlah Data Harus Lebih Dari 1", "Jumlah Data Tidak Mencukupi", JOptionPane.YES_NO_OPTION, JOptionPane.WARNING_MESSAGE, null, optionsArray, null);
            }
        }else{
            setE(false);
        }
    }
    public void isitabel (){
    Arrays.sort(data);
    int kategori = (int) op.kelas(data);
    int end=0;
    int start=0;
    for (int i = 0; i < kategori; i++) { //agar tidak melewati jumlah kelas (baris)
        Object[] dta = new Object[5];
        //interval
        if (start==0) {
            start= 0;
            end=data[start]+(((int)op.interval(data))-1);
            dta[0] = data[start] + " - " + end;
        } else {  
          end=start+(((int)op.interval(data))-1);
          dta[0] = start + " - " + end;
        }
        //frekuensi
        int count=0;
        for (int j = 0; j < data.length; j++) {
            if (data[j]>=start && data[j]<=end) {
                count++;
            }
        }
        //tepi bawah,tepi atas, nilai tengah
        if (start==0) {
            double tepibwh=data[0]-0.5;
            double tengah=(double)(data[0]+end)/2; //remember using (double) 
            dta[2]=tepibwh;
            dta[4]=tengah;
        }else{
          double tepibwh=start-0.5;  
          double tengah=(double)(start+end)/2; //remember using (double)
          dta[2]=tepibwh;
          dta[4]=tengah;
        }
        double tepiats=end+0.5;
        dta[1]=count;
        dta[3]=tepiats;
        tbmodel.addRow(dta);
        start=end+1;
    }
    }
    private void setE(boolean stt){
        //untuk mengatur tombol aktif atau tidak
        txganti.setEditable(stt);
        cganti.setEnabled(stt);
        cproses.setEnabled(stt);
        txganti1.setEditable(stt);
        cganti1.setEnabled(stt);
    }
    private void proses(){
        txmean.setText(Double.toString(op.mean(data)));        
        txmodus.setText(op.modus(data));
        txmedian.setText(Double.toString(op.median(data)));
        txkelas.setText(Double.toString(op.kelas(data)));
        txinterval.setText(Double.toString(op.interval(data)));
        txrerata.setText(Double.toString(op.rerata(data)));
        txvarians.setText(Double.toString(op.varians(data)));
        String var=txvarians.getText();
        double vari=Double.parseDouble(var);
        txbaku.setText(Double.toString(op.baku(data,vari)));
        tbmodel.getDataVector().removeAllElements();
        isitabel();
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cganti;
    private javax.swing.JButton cganti1;
    private javax.swing.JButton cproses;
    private javax.swing.JButton csimpan;
    private javax.swing.JButton ctutup;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tbfrekuensi;
    private javax.swing.JTextField txbaku;
    private javax.swing.JTextField txganti;
    private javax.swing.JTextField txganti1;
    private javax.swing.JTextField txinterval;
    private javax.swing.JTextField txkelas;
    private javax.swing.JTextField txmean;
    private javax.swing.JTextField txmedian;
    private javax.swing.JTextField txmodus;
    private javax.swing.JTextField txrerata;
    private javax.swing.JTextField txvarians;
    // End of variables declaration//GEN-END:variables

}
